DROP TABLE IF EXISTS prices;

DROP TABLE IF EXISTS coins;

CREATE TABLE coins (
    id UUID PRIMARY KEY,
    symbol VARCHAR(10) NOT NULL UNIQUE,
    observed BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE prices (
    id UUID PRIMARY KEY,
    coin_id UUID NOT NULL,
    price VARCHAR(50) NOT NULL,
    timestamp INT NOT NULL
);

ALTER TABLE prices
ADD CONSTRAINT fk_price_coin FOREIGN KEY (coin_id) REFERENCES coins (id) ON UPDATE CASCADE ON DELETE CASCADE;