DROP TABLE IF EXISTS price;

DROP TABLE IF EXISTS coin;

CREATE TABLE coin (
    id UUID PRIMARY KEY,
    symbol VARCHAR(10) NOT NULL UNIQUE,
    observed BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE price (
    id UUID PRIMARY KEY,
    coin_id UUID NOT NULL,
    timestamp INT NOT NULL
);

ALTER TABLE price
ADD CONSTRAINT fk_price_coin FOREIGN KEY (coin_id) REFERENCES coin (id) ON UPDATE CASCADE ON DELETE CASCADE;